# Generated by Django 4.0.4 on 2022-04-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='name',
            field=models.CharField(default='Male', max_length=32),
        ),
    ]
