# Generated by Django 4.0.4 on 2022-04-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0002_gender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='costumers/images'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='gender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costumer.gender'),
        ),
    ]
